AUT=bravo --disable-watchdog --watchdog-timeout=10 --disable-integrity-check --disable-fiber-use-check --disable-firmware-check --disable-ssm --disable-ports-check
ENVVARS=envvars
HOOK_SUB_PROCESSES=true
IMPLICITAUTSTART=1
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_LoginScreen "tst_GEM-LOC-CROATIA-Stone – Treatment"
VERSION=3
WRAPPERS=Qt
