AUT=bravo --disable-watchdog --watchdog-timeout=10 --disable-integrity-check --disable-fiber-use-check --disable-firmware-check --disable-ssm --disable-ports-check
ENVVARS=envvars
HOOK_SUB_PROCESSES=true
IMPLICITAUTSTART=1
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES="tst_Home Screen" tst_SoftTissue-Guided tst_Stone-Guided "tst_Soft Tissue Guided Treatment Screen" "tst_Stone – Treatment" "tst_Stone Sense Treatment Screen"
VERSION=3
WRAPPERS=Qt
