# -*- coding: utf-8 -*-

import names


def main():
    doubleClick(waitForObject(names.numpad_pushButton_8_NumpadButton), 56, 64, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.numpad_pushButton_8_NumpadButton))
    clickButton(waitForObject(names.numpad_pushButton_8_NumpadButton))
    clickButton(waitForObject(names.mainFrame_okButton_QPushButton))
    clickButton(waitForObject(names.homeScreen_settingsButton_QPushButton))
    clickTab(waitForObject(names.settingsScreen_tbSystemInfo_TabWidget), "INFO")
    clickButton(waitForObject(names.gbSystemInformation_pbLanguageSettingsUpdate_QPushButton))
    clickButton(waitForObject(names.languagesFrame_pbEstonia_QPushButton))
    mouseClick(waitForObject(names.centralWidget_QFrame_2), 1084, 696, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.buttonsFrame_acceptButton_QPushButton))
    clickButton(waitForObject(names.buttonsBar_homeButton_QPushButton))
    clickButton(waitForObject(names.gbExpert_expertButton_QPushButton))
    mouseClick(waitForObject(names.modeButton_nameLabel_QLabel), 95, 29, Qt.NoModifier, Qt.LeftButton)
    test.compare(str(waitForObjectExists(names.centralWidget_lbTitle_QLabel).text), "VALI REŽIIM")
    test.compare(str(waitForObjectExists(names.centralWidget_label_2_QLabel).text), "STANDARDNE")
    test.compare(str(waitForObjectExists(names.centralWidget_Square_QPushButton).text), "REGULAARNE\nPULSS")
    test.compare(str(waitForObjectExists(names.centralWidget_CW_QPushButton).text), "PIDEV\nLAINE\n(CW)")
    test.compare(str(waitForObjectExists(names.centralWidget_label_QLabel).text), "TÄIUSTATUD")
    test.compare(str(waitForObjectExists(names.centralWidget_MRP_QPushButton).text), "MINIMAALNE\nRETROPULSIOON™")
    test.compare(str(waitForObjectExists(names.centralWidget_Fragmentation_QPushButton).text), "PURUSTUSIMPULSS™")
    test.compare(str(waitForObjectExists(names.centralWidget_Cleaning_QPushButton).text), "MINIMAALNE\nKARBONISEERIMISIMPULSS™")
    test.compare(str(waitForObjectExists(names.centralWidget_Enucleation_QPushButton).text), "ENUKLEATSIOONIMPULSS™")
    mouseClick(waitForObject(names.centralWidget_mainWidget_QWidget), 401, 534, Qt.NoModifier, Qt.LeftButton)
    sendEvent("QWheelEvent", waitForObject(names.centralWidget_mainWidget_QWidget), 401, 534, -120, 0, 2)
    test.compare(str(waitForObjectExists(names.buttonsFrame_rejectButton_QPushButton).text), "TÜHISTA")
    mouseClick(waitForObject(names.centralWidget_label_2_QLabel), 441, 37, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.square_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "REGULAARNE PULSS")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Standardne impulsi kuju lameda ülaimpulsina, mida kasutatakse litotripsia ja pehmete kudede protseduuride jaoks.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    clickButton(waitForObject(names.cW_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "PIDEV LAINE (CW)")
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "PIDEV LAINE (CW)")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Pidev ja katkematu laservõimsus pehmete kudede protseduurideks, näiteks kudede aurustamiseks ja koagulatsiooniks.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    clickButton(waitForObject(names.mRP_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "MINIMAALNE RETROPULSIOON™")
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "MINIMAALNE RETROPULSIOON™")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Spetsiaalne impulsi kuju, mis on optimeeritud retropulsiooni vähendamiseks litotripsia ajal.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    clickButton(waitForObject(names.mRP_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "MINIMAALNE RETROPULSIOON™")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Spetsiaalne impulsi kuju, mis on optimeeritud retropulsiooni vähendamiseks litotripsia ajal.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    clickButton(waitForObject(names.fragmentation_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "PURUSTUSIMPULSS™")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Spetsiaalne impulsi kuju, mis on välja töötatud kivide kiireks ablatsiooniks suurteks kildudeks.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    mouseClick(waitForObject(names.centralWidget_mainWidget_QWidget), 350, 522, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.cleaning_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "MINIMAALNE KARBONISEERIMISIMPULSS™")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Spetsiaalne impulsi kuju pehmete kudede sisselõikamiseks ja ekstsisiooniks, mis minimeerib kudede karboniseerumist.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
    clickButton(waitForObject(names.enucleation_icon_QPushButton))
    test.compare(str(waitForObjectExists(names.centralWidget_TitleLabel_QLabel_2).text), "ENUKLEATSIOONIMPULSS™")
    test.compare(str(waitForObjectExists(names.centralWidget_MessageLabel_QLabel_2).text), "Spetsiaalne impulsi kuju enukleatsiooniprotseduuri jaoks, mis maksimeerib adenoomilise koe ja kapsli termomehaanilist eraldamist ning tagab samal ajal tugeva hemostaasi.")
    test.compare(str(waitForObjectExists(names.centralWidget_OKButton_QPushButton).text), "OK")
    clickButton(waitForObject(names.centralWidget_OKButton_QPushButton))
