# encoding: UTF-8

from objectmaphelper import *

o_ScreenSwitcher = {"type": "ScreenSwitcher", "unnamed": 1, "visible": 1}
loginScreen_LoginScreen = {"name": "LoginScreen", "type": "LoginScreen", "visible": 1, "window": o_ScreenSwitcher}
loginScreen_mainFrame_QFrame = {"container": loginScreen_LoginScreen, "name": "mainFrame", "type": "QFrame", "visible": 1}
mainFrame_gbPasscode_QGroupBox = {"container": loginScreen_mainFrame_QFrame, "name": "gbPasscode", "type": "QGroupBox", "visible": 1}
gbPasscode_inputFrame_PasscodeInputWidget = {"container": mainFrame_gbPasscode_QGroupBox, "name": "inputFrame", "type": "PasscodeInputWidget", "visible": 1}
inputFrame_numpad_Numpad = {"container": gbPasscode_inputFrame_PasscodeInputWidget, "name": "numpad", "type": "Numpad", "visible": 1}
numpad_pushButton_4_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_4", "type": "NumpadButton", "visible": 1}
numpad_pushButton_8_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_8", "type": "NumpadButton", "visible": 1}
fiberVerificationWarningDialog_FiberVerificationWarningDialog = {"name": "FiberVerificationWarningDialog", "type": "FiberVerificationWarningDialog", "visible": 1}
fiberVerificationWarningDialog_mainFrame_QFrame = {"name": "mainFrame", "type": "QFrame", "visible": 1, "window": fiberVerificationWarningDialog_FiberVerificationWarningDialog}
mainFrame_okButton_QPushButton = {"container": fiberVerificationWarningDialog_mainFrame_QFrame, "name": "okButton", "type": "QPushButton", "visible": 1}
o_MessageBoxAlert = {"type": "MessageBoxAlert", "unnamed": 1, "visible": 1}
centralWidget_QFrame = {"name": "centralWidget", "type": "QFrame", "visible": 1, "window": o_MessageBoxAlert}
centralWidget_okButton_QPushButton = {"container": centralWidget_QFrame, "name": "okButton", "type": "QPushButton", "visible": 1}
homeScreen_HomeScreen = {"name": "HomeScreen", "type": "HomeScreen", "visible": 1, "window": o_ScreenSwitcher}
homeScreen_logoffButton_QPushButton = {"container": homeScreen_HomeScreen, "name": "logoffButton", "type": "QPushButton", "visible": 1}
logOffSystem_QuestionDialog = {"name": "logOffSystem", "type": "QuestionDialog", "visible": 1}
logOffSystem_centralWidget_QFrame = {"name": "centralWidget", "type": "QFrame", "visible": 1, "window": logOffSystem_QuestionDialog}
centralWidget_lbDialogTitle_QLabel = {"container": logOffSystem_centralWidget_QFrame, "name": "lbDialogTitle", "type": "QLabel", "visible": 1}
centralWidget_buttonsFrame_QFrame = {"container": logOffSystem_centralWidget_QFrame, "name": "buttonsFrame", "type": "QFrame", "visible": 1}
buttonsFrame_acceptButton_QPushButton = {"container": centralWidget_buttonsFrame_QFrame, "name": "acceptButton", "type": "QPushButton", "visible": 1}
numpad_pushButton_5_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_5", "type": "NumpadButton", "visible": 1}
numpad_pushButton_6_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_6", "type": "NumpadButton", "visible": 1}
inputFrame_invalidPassNotif_QLabel = {"container": gbPasscode_inputFrame_PasscodeInputWidget, "name": "invalidPassNotif", "type": "QLabel", "visible": 1}
mainFrame_messageLabel_QLabel = {"container": fiberVerificationWarningDialog_mainFrame_QFrame, "name": "messageLabel", "type": "QLabel", "visible": 1}
centralWidget_lbPictureOverQuestionText_QLabel = {"container": logOffSystem_centralWidget_QFrame, "name": "lbPictureOverQuestionText", "type": "QLabel", "visible": 1}
centralWidget_questionLabel_QLabel = {"container": logOffSystem_centralWidget_QFrame, "name": "questionLabel", "type": "QLabel", "visible": 1}
homeScreen_topBar_TopBar = {"container": homeScreen_HomeScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar = {"container": homeScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
homeScreen_pbSoftTissueQuickStart_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbSoftTissueQuickStart", "type": "QToolButton", "visible": 1}
quickStartScreen_QuickStartScreen = {"name": "QuickStartScreen", "type": "QuickStartScreen", "visible": 1, "window": o_ScreenSwitcher}
quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget = {"container": quickStartScreen_QuickStartScreen, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdLeftPedalTreatmentLayout_QWidget = {"container": quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdLeftPedalTreatmentLayout", "type": "QWidget", "visible": 1}
wdLeftPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdLeftPedalTreatmentLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabLeftMainPresets_QWidget = {"container": wdLeftPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabLeftMainPresets", "type": "QWidget", "visible": 1}
tabLeftMainPresets_leftPresetsView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabLeftMainPresets_QWidget, "name": "leftPresetsView", "type": "PresetListView", "visible": 1}
quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget_2 = {"container": quickStartScreen_QuickStartScreen, "name": "qt_tabwidget_stackedwidget", "occurrence": 3, "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdRightPedalTreatmentLayout_QWidget = {"container": quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget_2, "name": "wdRightPedalTreatmentLayout", "type": "QWidget", "visible": 1}
wdRightPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdRightPedalTreatmentLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabRightMainPresets_QWidget = {"container": wdRightPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabRightMainPresets", "type": "QWidget", "visible": 1}
tabRightMainPresets_rightPresetsView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabRightMainPresets_QWidget, "name": "rightPresetsView", "type": "PresetListView", "visible": 1}
quickStartScreen_pbContinue_QPushButton = {"container": quickStartScreen_QuickStartScreen, "name": "pbContinue", "type": "QPushButton", "visible": 1}
recommendedFiberWarningDialog_RecommendedFiberWarningDialog = {"name": "RecommendedFiberWarningDialog", "type": "RecommendedFiberWarningDialog", "visible": 1}
recommendedFiberWarningDialog_mainFrame_QFrame = {"name": "mainFrame", "type": "QFrame", "visible": 1, "window": recommendedFiberWarningDialog_RecommendedFiberWarningDialog}
mainFrame_messageLabel_QLabel_2 = {"container": recommendedFiberWarningDialog_mainFrame_QFrame, "name": "messageLabel", "type": "QLabel", "visible": 1}
mainFrame_okButton_QPushButton_2 = {"container": recommendedFiberWarningDialog_mainFrame_QFrame, "name": "okButton", "type": "QPushButton", "visible": 1}
treatmentScreen_TreatmentScreen = {"name": "TreatmentScreen", "type": "TreatmentScreen", "visible": 1, "window": o_ScreenSwitcher}
treatmentScreen_topBar_TopBar = {"container": treatmentScreen_TreatmentScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar_2 = {"container": treatmentScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
buttonsBar_homeButton_QPushButton = {"container": topBar_buttonsBar_ButtonsBar_2, "name": "homeButton", "type": "QPushButton", "visible": 1}
homeScreen_pbSoftTissueAssistant_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbSoftTissueAssistant", "type": "QToolButton", "visible": 1}
softTissueAssistantModeScreen_SoftTissueAssistantModeScreen = {"name": "SoftTissueAssistantModeScreen", "type": "SoftTissueAssistantModeScreen", "visible": 1, "window": o_ScreenSwitcher}
softTissueAssistantModeScreen_gbSoftTissueProcedures_QFrame = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "gbSoftTissueProcedures", "type": "QFrame", "visible": 1}
gbSoftTissueProcedures_pbIncision_QPushButton = {"container": softTissueAssistantModeScreen_gbSoftTissueProcedures_QFrame, "name": "pbIncision", "type": "QPushButton", "visible": 1}
softTissueAssistantModeScreen_pbContinue_QPushButton = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "pbContinue", "type": "QPushButton", "visible": 1}
treatmentScreen_TreatmentCharacteristicsBar_SoftTissueCharacteristicsBar = {"container": treatmentScreen_TreatmentScreen, "name": "TreatmentCharacteristicsBar", "type": "SoftTissueCharacteristicsBar", "visible": 1}
treatmentCharacteristicsBar_pbEdit_QPushButton = {"container": treatmentScreen_TreatmentCharacteristicsBar_SoftTissueCharacteristicsBar, "name": "pbEdit", "type": "QPushButton", "visible": 1}
o_SoftTissueCharacteristicsDialog = {"type": "SoftTissueCharacteristicsDialog", "unnamed": 1, "visible": 1}
centralWidget_QFrame_2 = {"name": "centralWidget", "type": "QFrame", "visible": 1, "window": o_SoftTissueCharacteristicsDialog}
treatmentScreen_leftPedalWidget_PresetTabWidget = {"container": treatmentScreen_TreatmentScreen, "name": "leftPedalWidget", "type": "PresetTabWidget", "visible": 1}
leftPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget = {"container": treatmentScreen_leftPedalWidget_PresetTabWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget = {"container": leftPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget, "name": "OperationPresetWidget", "type": "OperationPresetWidget", "visible": 1}
operationPresetWidget_modeWidget_QFrame = {"container": qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget, "name": "modeWidget", "type": "QFrame", "visible": 1}
modeWidget_PulseModeWidget_PulseModeWidget = {"container": operationPresetWidget_modeWidget_QFrame, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_peakPowerButton_ParameterSettingsButton = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "peakPowerButton", "type": "ParameterSettingsButton", "visible": 1}
peakPowerButton_iconLabel_QLabel = {"container": pulseModeWidget_peakPowerButton_ParameterSettingsButton, "name": "iconLabel", "type": "QLabel", "visible": 1}
centralWidget_QFrame_3 = {"name": "centralWidget", "type": "QFrame", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_mainWidget_QWidget = {"container": centralWidget_QFrame_3, "name": "mainWidget", "type": "QWidget", "visible": 1}
centralWidget_buttonsFrame_QFrame_2 = {"container": centralWidget_QFrame_3, "name": "buttonsFrame", "type": "QFrame", "visible": 1}
buttonsFrame_rejectButton_QPushButton = {"container": centralWidget_buttonsFrame_QFrame_2, "name": "rejectButton", "type": "QPushButton", "visible": 1}
centralWidget_acceptButton_QPushButton = {"container": centralWidget_QFrame_2, "name": "acceptButton", "type": "QPushButton", "visible": 1}
softTissueAssistantModeScreen_wdTabWidgets_QWidget = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "wdTabWidgets", "type": "QWidget", "visible": 1}
homeScreen_pbStoneAssistant_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbStoneAssistant", "type": "QToolButton", "visible": 1}
stoneAssistantModeScreen_StoneAssistantModeScreen = {"name": "StoneAssistantModeScreen", "type": "StoneAssistantModeScreen", "visible": 1, "window": o_ScreenSwitcher}
stoneAssistantModeScreen_locationFrame_QFrame = {"container": stoneAssistantModeScreen_StoneAssistantModeScreen, "name": "locationFrame", "type": "QFrame", "visible": 1}
locationFrame_kidneyPcnlLocationButton_QPushButton = {"container": stoneAssistantModeScreen_locationFrame_QFrame, "name": "kidneyPcnlLocationButton", "type": "QPushButton", "visible": 1}
stoneAssistantModeScreen_flowRateFrame_QFrame = {"container": stoneAssistantModeScreen_StoneAssistantModeScreen, "name": "flowRateFrame", "type": "QFrame", "visible": 1}
flowRateFrame_lowFlowRateButton_QPushButton = {"container": stoneAssistantModeScreen_flowRateFrame_QFrame, "name": "lowFlowRateButton", "type": "QPushButton", "visible": 1}
stoneAssistantModeScreen_hardnessFrame_QFrame = {"container": stoneAssistantModeScreen_StoneAssistantModeScreen, "name": "hardnessFrame", "type": "QFrame", "visible": 1}
hardnessFrame_smallHardnessButton_QPushButton = {"container": stoneAssistantModeScreen_hardnessFrame_QFrame, "name": "smallHardnessButton", "type": "QPushButton", "visible": 1}
stoneAssistantModeScreen_centralWidget_QWidget = {"container": stoneAssistantModeScreen_StoneAssistantModeScreen, "name": "centralWidget", "type": "QWidget", "visible": 1}
homeScreen_gbExpert_QFrame = {"container": homeScreen_HomeScreen, "name": "gbExpert", "type": "QFrame", "visible": 1}
gbExpert_expertButton_QPushButton = {"container": homeScreen_gbExpert_QFrame, "name": "expertButton", "type": "QPushButton", "visible": 1}
treatmentScreen_rightPedalWidget_PresetTabWidget = {"container": treatmentScreen_TreatmentScreen, "name": "rightPedalWidget", "type": "PresetTabWidget", "visible": 1}
rightPedalWidget_wdPresetTabs_TabWidget = {"container": treatmentScreen_rightPedalWidget_PresetTabWidget, "name": "wdPresetTabs", "type": "TabWidget", "visible": 1}
treatmentScreen_bottomBar_QFrame = {"container": treatmentScreen_TreatmentScreen, "name": "bottomBar", "type": "QFrame", "visible": 1}
bottomBar_totalTimeFrame_ParameterValueBottomBarWidget = {"container": treatmentScreen_bottomBar_QFrame, "name": "totalTimeFrame", "type": "ParameterValueBottomBarWidget", "visible": 1}
totalTimeFrame_nameLabel_QLabel = {"container": bottomBar_totalTimeFrame_ParameterValueBottomBarWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
leftPedalWidget_wdPresetTabs_TabWidget = {"container": treatmentScreen_leftPedalWidget_PresetTabWidget, "name": "wdPresetTabs", "type": "TabWidget", "visible": 1}
bottomBar_stateSwitch_StateSwitch = {"container": treatmentScreen_bottomBar_QFrame, "name": "stateSwitch", "type": "StateSwitch", "visible": 1}
stateSwitch_readyButton_QPushButton = {"container": bottomBar_stateSwitch_StateSwitch, "name": "readyButton", "type": "QPushButton", "visible": 1}
pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "pulseEnergyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
pulseEnergyWidgetEmission_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
rightPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget = {"container": treatmentScreen_rightPedalWidget_PresetTabWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget_2 = {"container": rightPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget, "name": "OperationPresetWidget", "type": "OperationPresetWidget", "visible": 1}
operationPresetWidget_modeWidget_QFrame_2 = {"container": qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget_2, "name": "modeWidget", "type": "QFrame", "visible": 1}
modeWidget_PulseModeWidget_PulseModeWidget_2 = {"container": operationPresetWidget_modeWidget_QFrame_2, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "pulseEnergyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
homeScreen_settingsButton_QPushButton = {"container": homeScreen_HomeScreen, "name": "settingsButton", "type": "QPushButton", "visible": 1}
settingsScreen_SettingsScreen = {"name": "SettingsScreen", "type": "SettingsScreen", "visible": 1, "window": o_ScreenSwitcher}
settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget = {"container": settingsScreen_SettingsScreen, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdSystemSettingsLayout_QWidget = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdSystemSettingsLayout", "type": "QWidget", "visible": 1}
wdSystemSettingsLayout_systemsettingframe_QFrame = {"container": qt_tabwidget_stackedwidget_wdSystemSettingsLayout_QWidget, "name": "systemsettingframe", "type": "QFrame", "visible": 1}
systemsettingframe_lbBrightnessName_QLabel = {"container": wdSystemSettingsLayout_systemsettingframe_QFrame, "name": "lbBrightnessName", "type": "QLabel", "visible": 1}
wdSystemSettingsLayout_aimingbeamsettingframe_QFrame = {"container": qt_tabwidget_stackedwidget_wdSystemSettingsLayout_QWidget, "name": "aimingbeamsettingframe", "type": "QFrame", "visible": 1}
aimingbeamsettingframe_lbAimingBeamDefaultModeName_QLabel = {"container": wdSystemSettingsLayout_aimingbeamsettingframe_QFrame, "name": "lbAimingBeamDefaultModeName", "type": "QLabel", "visible": 1}
settingsScreen_tbSystemInfo_TabWidget = {"container": settingsScreen_SettingsScreen, "name": "tbSystemInfo", "type": "TabWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdSystemInfoLayout", "type": "QWidget", "visible": 1}
wdSystemInfoLayout_gbSystemInformation_QGroupBox = {"container": qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget, "name": "gbSystemInformation", "type": "QGroupBox", "visible": 1}
wdSystemInfoLayout_gbFiberInformation_QGroupBox = {"container": qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget, "name": "gbFiberInformation", "type": "QGroupBox", "visible": 1}
qt_tabwidget_stackedwidget_wdEventLogsLayout_QFrame = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdEventLogsLayout", "type": "QFrame", "visible": 1}
wdEventLogsLayout_SystemEventErrorLogWidget_SystemEventErrorLogWidget = {"container": qt_tabwidget_stackedwidget_wdEventLogsLayout_QFrame, "name": "SystemEventErrorLogWidget", "type": "SystemEventErrorLogWidget", "visible": 1}
systemEventErrorLogWidget_tableView_QTableView = {"container": wdEventLogsLayout_SystemEventErrorLogWidget_SystemEventErrorLogWidget, "name": "tableView", "type": "QTableView", "visible": 1}
settingsScreen_addButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "addButton", "type": "QPushButton", "visible": 1}
centralWidget_PulseModeWidget_PulseModeWidget = {"container": centralWidget_QFrame_3, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "averagePowerWidget", "type": "ParameterWithEnumerableValueWidget", "visible": 1}
averagePowerWidget_progressFrame_QFrame = {"container": pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget, "name": "progressFrame", "type": "QFrame", "visible": 1}
centralWidget_pbName_QPushButton = {"container": centralWidget_QFrame_3, "name": "pbName", "type": "QPushButton", "visible": 1}
keyboardPopup_KeyboardPopup = {"name": "KeyboardPopup", "type": "KeyboardPopup", "visible": 1}
keyboardPopup_wdEdit_WdLineEdit = {"container": keyboardPopup_KeyboardPopup, "name": "wdEdit", "type": "WdLineEdit", "visible": 1}
keyboardPopup_a_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "a", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_a_KeyButton_2 = {"aboveWidget": keyboardPopup_a_KeyButton, "container": keyboardPopup_KeyboardPopup, "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_A_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "A", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_U_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "U", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_T_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "T", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_lbText_QLabel = {"container": keyboardPopup_KeyboardPopup, "name": "lbText", "occurrence": 2, "type": "QLabel", "visible": 1}
pulseModeWidget_saveButton_QPushButton = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "saveButton", "type": "QPushButton", "visible": 1}
settingsScreen_editButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "editButton", "type": "QPushButton", "visible": 1}
qt_tabwidget_stackedwidget_wdPresetsLayout_QWidget = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdPresetsLayout", "type": "QWidget", "visible": 1}
wdPresetsLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdPresetsLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabSettingsPresetsUserStonePresets_QWidget = {"container": wdPresetsLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabSettingsPresetsUserStonePresets", "type": "QWidget", "visible": 1}
tabSettingsPresetsUserStonePresets_presetListView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabSettingsPresetsUserStonePresets_QWidget, "name": "presetListView", "type": "PresetListView", "visible": 1}
centralWidget_lbOperation_QLabel = {"container": centralWidget_QFrame_3, "name": "lbOperation", "type": "QLabel", "visible": 1}
settingsScreen_deletePresetButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "deletePresetButton", "type": "QPushButton", "visible": 1}
centralWidget_questionLabel_QLabel_2 = {"container": centralWidget_QFrame_3, "name": "questionLabel", "type": "QLabel", "visible": 1}
buttonsFrame_acceptButton_QPushButton_2 = {"container": centralWidget_buttonsFrame_QFrame_2, "name": "acceptButton", "type": "QPushButton", "visible": 1}
keyboardPopup_u_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "u", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_t_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "t", "type": "KeyButton", "unnamed": 1, "visible": 1}
centralWidget_lbDialogTitle_QLabel_2 = {"container": centralWidget_QFrame_3, "name": "lbDialogTitle", "type": "QLabel", "visible": 1}
settingsScreen_tabBarSystemInfo_TabBar = {"container": settingsScreen_SettingsScreen, "name": "tabBarSystemInfo", "type": "TabBar", "visible": 1}
tabBarSystemInfo_USER_PRESETS_TabItem = {"container": settingsScreen_tabBarSystemInfo_TabBar, "text": "USER\nPRESETS", "type": "TabItem"}
settingsScreen_wdBottom_QWidget = {"container": settingsScreen_SettingsScreen, "name": "wdBottom", "type": "QWidget", "visible": 1}
homeScreen_logButton_QPushButton = {"container": homeScreen_HomeScreen, "name": "logButton", "type": "QPushButton", "visible": 1}
treatmentLogScreen_TreatmentLogScreen = {"name": "TreatmentLogScreen", "type": "TreatmentLogScreen", "visible": 1, "window": o_ScreenSwitcher}
treatmentLogScreen_tvLogsTable_QTreeView = {"container": treatmentLogScreen_TreatmentLogScreen, "name": "tvLogsTable", "type": "QTreeView", "visible": 1}
tvLogsTable_QHeaderView = {"container": treatmentLogScreen_tvLogsTable_QTreeView, "orientation": 1, "type": "QHeaderView", "unnamed": 1, "visible": 1}
treatmentLogScreen_wdBottom_QWidget = {"container": treatmentLogScreen_TreatmentLogScreen, "name": "wdBottom", "type": "QWidget", "visible": 1}
stoneAssistantModeScreen_continueButton_QPushButton = {"container": stoneAssistantModeScreen_StoneAssistantModeScreen, "name": "continueButton", "type": "QPushButton", "visible": 1}
treatmentScreen_StoneSenseFrame_StoneSenseFrame = {"container": treatmentScreen_TreatmentScreen, "name": "StoneSenseFrame", "type": "StoneSenseFrame", "visible": 1}
stoneSenseFrame_pbStoneSense_QPushButton = {"container": treatmentScreen_StoneSenseFrame_StoneSenseFrame, "name": "pbStoneSense", "type": "QPushButton", "visible": 1}
calibrationPopupDialog_CalibrationPopupDialog = {"name": "CalibrationPopupDialog", "type": "CalibrationPopupDialog", "visible": 1, "window": o_ScreenSwitcher}
calibrationPopupDialog_pMessageFrame_QFrame = {"container": calibrationPopupDialog_CalibrationPopupDialog, "name": "pMessageFrame", "type": "QFrame", "visible": 1}
pMessageFrame_pInitiateCalibrationFrame_InitiateCalibrationDialog = {"container": calibrationPopupDialog_pMessageFrame_QFrame, "name": "pInitiateCalibrationFrame", "type": "InitiateCalibrationDialog", "visible": 1}
pInitiateCalibrationFrame_pCalibrationMessageLabel_QLabel = {"container": pMessageFrame_pInitiateCalibrationFrame_InitiateCalibrationDialog, "name": "pCalibrationMessageLabel", "type": "QLabel", "visible": 1}
pInitiateCalibrationFrame_checkBoxFrame_QFrame = {"container": pMessageFrame_pInitiateCalibrationFrame_InitiateCalibrationDialog, "name": "checkBoxFrame", "type": "QFrame", "visible": 1}
calibrationPopupDialog_pbMiddleButton_QPushButton = {"container": calibrationPopupDialog_CalibrationPopupDialog, "name": "pbMiddleButton", "type": "QPushButton", "visible": 1}
pMessageFrame_pCalibrationSuccessFrame_CalibrationSuccessDialog = {"container": calibrationPopupDialog_pMessageFrame_QFrame, "name": "pCalibrationSuccessFrame", "type": "CalibrationSuccessDialog", "visible": 1}
pCalibrationSuccessFrame_frame_QFrame = {"container": pMessageFrame_pCalibrationSuccessFrame_CalibrationSuccessDialog, "name": "frame", "type": "QFrame", "visible": 1}
frame_pStoneSenseTextLabel_QLabel = {"container": pCalibrationSuccessFrame_frame_QFrame, "name": "pStoneSenseTextLabel", "type": "QLabel", "visible": 1}
pCalibrationSuccessFrame_pOKButton_QPushButton = {"container": pMessageFrame_pCalibrationSuccessFrame_CalibrationSuccessDialog, "name": "pOKButton", "type": "QPushButton", "visible": 1}
centralWidget_MessageLabel_QLabel = {"container": centralWidget_QFrame_3, "name": "MessageLabel", "type": "QLabel", "visible": 1}
centralWidget_DisableButton_QPushButton = {"container": centralWidget_QFrame_3, "name": "DisableButton", "type": "QPushButton", "visible": 1}
pInitiateCalibrationFrame_frame_QFrame = {"container": pMessageFrame_pInitiateCalibrationFrame_InitiateCalibrationDialog, "name": "frame", "type": "QFrame", "visible": 1}
frame_emissionTextIcon_QLabel = {"container": pInitiateCalibrationFrame_frame_QFrame, "name": "emissionTextIcon", "type": "QLabel", "visible": 1}
frame_pProgressFrame_QFrame = {"container": pInitiateCalibrationFrame_frame_QFrame, "name": "pProgressFrame", "type": "QFrame", "visible": 1}
pProgressFrame_pTimerLabel_QLabel = {"container": frame_pProgressFrame_QFrame, "name": "pTimerLabel", "type": "QLabel", "visible": 1}
frame_pAnimationLabel_QLabel = {"container": pCalibrationSuccessFrame_frame_QFrame, "name": "pAnimationLabel", "type": "QLabel", "visible": 1}
pCalibrationSuccessFrame_pEmissionLabel_QLabel = {"container": pMessageFrame_pCalibrationSuccessFrame_CalibrationSuccessDialog, "name": "pEmissionLabel", "type": "QLabel", "visible": 1}
centralWidget_TitleLabel_QLabel = {"container": centralWidget_QFrame_3, "name": "TitleLabel", "type": "QLabel", "visible": 1}
calibrationPopupDialog_pbFailedCalibrationButton_QPushButton = {"container": calibrationPopupDialog_CalibrationPopupDialog, "name": "pbFailedCalibrationButton", "type": "QPushButton", "visible": 1}
pMessageFrame_pCalibrationErrorFrame_CalibrationErrorDialog = {"container": calibrationPopupDialog_pMessageFrame_QFrame, "name": "pCalibrationErrorFrame", "type": "CalibrationErrorDialog", "visible": 1}
pCalibrationErrorFrame_pErrorMessageLabel_QLabel = {"container": pMessageFrame_pCalibrationErrorFrame_CalibrationErrorDialog, "name": "pErrorMessageLabel", "type": "QLabel", "visible": 1}
pCalibrationErrorFrame_pErrorAnimation_QLabel = {"container": pMessageFrame_pCalibrationErrorFrame_CalibrationErrorDialog, "name": "pErrorAnimation", "type": "QLabel", "visible": 1}
settingsScreen_pbBack_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "pbBack", "type": "QPushButton", "visible": 1}
homeScreen_pbStoneQuickStart_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbStoneQuickStart", "type": "QToolButton", "visible": 1}
pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "averagePowerWidget", "type": "ParameterWithEnumerableValueWidget", "visible": 1}
averagePowerWidget_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget_2, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget_3 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "averagePowerWidget", "type": "ParameterWithEnumerableValueWidget", "visible": 1}
bottomBar_lbPedalStatusIcon_QLabel = {"container": treatmentScreen_bottomBar_QFrame, "name": "lbPedalStatusIcon", "type": "QLabel", "visible": 1}
pulseModeWidget_buttonsWidget_QWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "buttonsWidget", "type": "QWidget", "visible": 1}
pulseModeWidget_buttonsWidget_QWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "buttonsWidget", "type": "QWidget", "visible": 1}
