# encoding: UTF-8

from objectmaphelper import *

o_ScreenSwitcher = {"type": "ScreenSwitcher", "unnamed": 1, "visible": 1}
loginScreen_LoginScreen = {"name": "LoginScreen", "type": "LoginScreen", "visible": 1, "window": o_ScreenSwitcher}
loginScreen_mainFrame_QFrame = {"container": loginScreen_LoginScreen, "name": "mainFrame", "type": "QFrame", "visible": 1}
mainFrame_gbPasscode_QGroupBox = {"container": loginScreen_mainFrame_QFrame, "name": "gbPasscode", "type": "QGroupBox", "visible": 1}
gbPasscode_inputFrame_PasscodeInputWidget = {"container": mainFrame_gbPasscode_QGroupBox, "name": "inputFrame", "type": "PasscodeInputWidget", "visible": 1}
inputFrame_numpad_Numpad = {"container": gbPasscode_inputFrame_PasscodeInputWidget, "name": "numpad", "type": "Numpad", "visible": 1}
numpad_pushButton_8_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_8", "type": "NumpadButton", "visible": 1}
fiberVerificationWarningDialog_FiberVerificationWarningDialog = {"name": "FiberVerificationWarningDialog", "type": "FiberVerificationWarningDialog", "visible": 1}
fiberVerificationWarningDialog_mainFrame_QFrame = {"name": "mainFrame", "type": "QFrame", "visible": 1, "window": fiberVerificationWarningDialog_FiberVerificationWarningDialog}
mainFrame_okButton_QPushButton = {"container": fiberVerificationWarningDialog_mainFrame_QFrame, "name": "okButton", "type": "QPushButton", "visible": 1}
homeScreen_HomeScreen = {"name": "HomeScreen", "type": "HomeScreen", "visible": 1, "window": o_ScreenSwitcher}
homeScreen_settingsButton_QPushButton = {"container": homeScreen_HomeScreen, "name": "settingsButton", "type": "QPushButton", "visible": 1}
settingsScreen_SettingsScreen = {"name": "SettingsScreen", "type": "SettingsScreen", "visible": 1, "window": o_ScreenSwitcher}
settingsScreen_tbSystemInfo_TabWidget = {"container": settingsScreen_SettingsScreen, "name": "tbSystemInfo", "type": "TabWidget", "visible": 1}
settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget = {"container": settingsScreen_SettingsScreen, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdSystemInfoLayout", "type": "QWidget", "visible": 1}
wdSystemInfoLayout_gbSystemInformation_QGroupBox = {"container": qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget, "name": "gbSystemInformation", "type": "QGroupBox", "visible": 1}
gbSystemInformation_pbLanguageSettingsUpdate_QPushButton = {"container": wdSystemInfoLayout_gbSystemInformation_QGroupBox, "name": "pbLanguageSettingsUpdate", "type": "QPushButton", "visible": 1}
wdSystemInfoLayout_centralWidget_QFrame = {"container": qt_tabwidget_stackedwidget_wdSystemInfoLayout_QWidget, "name": "centralWidget", "type": "QFrame", "visible": 1}
centralWidget_languagesFrame_QFrame = {"container": wdSystemInfoLayout_centralWidget_QFrame, "name": "languagesFrame", "type": "QFrame", "visible": 1}
languagesFrame_pbCroatia_QPushButton = {"container": centralWidget_languagesFrame_QFrame, "name": "pbCroatia", "type": "QPushButton", "visible": 1}
centralWidget_buttonsFrame_QFrame = {"container": wdSystemInfoLayout_centralWidget_QFrame, "name": "buttonsFrame", "type": "QFrame", "visible": 1}
buttonsFrame_acceptButton_QPushButton = {"container": centralWidget_buttonsFrame_QFrame, "name": "acceptButton", "type": "QPushButton", "visible": 1}
settingsScreen_topBar_TopBar = {"container": settingsScreen_SettingsScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar = {"container": settingsScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
buttonsBar_homeButton_QPushButton = {"container": topBar_buttonsBar_ButtonsBar, "name": "homeButton", "type": "QPushButton", "visible": 1}
homeScreen_pbSoftTissueQuickStart_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbSoftTissueQuickStart", "type": "QToolButton", "visible": 1}
quickStartScreen_QuickStartScreen = {"name": "QuickStartScreen", "type": "QuickStartScreen", "visible": 1, "window": o_ScreenSwitcher}
quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget = {"container": quickStartScreen_QuickStartScreen, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdLeftPedalTreatmentLayout_QWidget = {"container": quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdLeftPedalTreatmentLayout", "type": "QWidget", "visible": 1}
wdLeftPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdLeftPedalTreatmentLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabLeftMainPresets_QWidget = {"container": wdLeftPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabLeftMainPresets", "type": "QWidget", "visible": 1}
tabLeftMainPresets_leftPresetsView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabLeftMainPresets_QWidget, "name": "leftPresetsView", "type": "PresetListView", "visible": 1}
quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget_2 = {"container": quickStartScreen_QuickStartScreen, "name": "qt_tabwidget_stackedwidget", "occurrence": 3, "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_wdRightPedalTreatmentLayout_QWidget = {"container": quickStartScreen_qt_tabwidget_stackedwidget_QStackedWidget_2, "name": "wdRightPedalTreatmentLayout", "type": "QWidget", "visible": 1}
wdRightPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdRightPedalTreatmentLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabRightMainPresets_QWidget = {"container": wdRightPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabRightMainPresets", "type": "QWidget", "visible": 1}
tabRightMainPresets_rightPresetsView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabRightMainPresets_QWidget, "name": "rightPresetsView", "type": "PresetListView", "visible": 1}
quickStartScreen_pbContinue_QPushButton = {"container": quickStartScreen_QuickStartScreen, "name": "pbContinue", "type": "QPushButton", "visible": 1}
recommendedFiberWarningDialog_RecommendedFiberWarningDialog = {"name": "RecommendedFiberWarningDialog", "type": "RecommendedFiberWarningDialog", "visible": 1}
recommendedFiberWarningDialog_mainFrame_QFrame = {"name": "mainFrame", "type": "QFrame", "visible": 1, "window": recommendedFiberWarningDialog_RecommendedFiberWarningDialog}
mainFrame_okButton_QPushButton_2 = {"container": recommendedFiberWarningDialog_mainFrame_QFrame, "name": "okButton", "type": "QPushButton", "visible": 1}
treatmentScreen_TreatmentScreen = {"name": "TreatmentScreen", "type": "TreatmentScreen", "visible": 1, "window": o_ScreenSwitcher}
treatmentScreen_bottomBar_QFrame = {"container": treatmentScreen_TreatmentScreen, "name": "bottomBar", "type": "QFrame", "visible": 1}
bottomBar_stateSwitch_StateSwitch = {"container": treatmentScreen_bottomBar_QFrame, "name": "stateSwitch", "type": "StateSwitch", "visible": 1}
stateSwitch_readyButton_QPushButton = {"container": bottomBar_stateSwitch_StateSwitch, "name": "readyButton", "type": "QPushButton", "visible": 1}
treatmentScreen_leftPedalWidget_PresetTabWidget = {"container": treatmentScreen_TreatmentScreen, "name": "leftPedalWidget", "type": "PresetTabWidget", "visible": 1}
leftPedalWidget_TabBar = {"container": treatmentScreen_leftPedalWidget_PresetTabWidget, "type": "TabBar", "unnamed": 1, "visible": 1}
eNUKLEACIJA_PROSTATE_VELIKA_ENERGIJA_TabItem = {"container": leftPedalWidget_TabBar, "text": "ENUKLEACIJA PROSTATE-(VELIKA ENERGIJA)", "type": "TabItem"}
leftPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget = {"container": treatmentScreen_leftPedalWidget_PresetTabWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget = {"container": leftPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget, "name": "OperationPresetWidget", "type": "OperationPresetWidget", "visible": 1}
operationPresetWidget_modeWidget_QFrame = {"container": qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget, "name": "modeWidget", "type": "QFrame", "visible": 1}
modeWidget_PulseModeWidget_PulseModeWidget = {"container": operationPresetWidget_modeWidget_QFrame, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "averagePowerWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
averagePowerWidgetEmission_nameLabel_QLabel = {"container": pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "pulseEnergyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
pulseEnergyWidgetEmission_nameLabel_QLabel = {"container": pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "frequencyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
frequencyWidgetEmission_nameLabel_QLabel = {"container": pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_modeButtonEmission_ModeButton = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "modeButtonEmission", "type": "ModeButton", "visible": 1}
modeButtonEmission_nameLabel_QLabel = {"container": pulseModeWidget_modeButtonEmission_ModeButton, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_peakPowerButtonEmission_ParameterSettingsButton = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "peakPowerButtonEmission", "type": "ParameterSettingsButton", "visible": 1}
peakPowerButtonEmission_nameLabel_QLabel = {"container": pulseModeWidget_peakPowerButtonEmission_ParameterSettingsButton, "name": "nameLabel", "type": "QLabel", "visible": 1}
bottomBar_totalEnergyFrame_ParameterValueBottomBarWidget = {"container": treatmentScreen_bottomBar_QFrame, "name": "totalEnergyFrame", "type": "ParameterValueBottomBarWidget", "visible": 1}
totalEnergyFrame_nameLabel_QLabel = {"container": bottomBar_totalEnergyFrame_ParameterValueBottomBarWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
bottomBar_totalTimeFrame_ParameterValueBottomBarWidget = {"container": treatmentScreen_bottomBar_QFrame, "name": "totalTimeFrame", "type": "ParameterValueBottomBarWidget", "visible": 1}
totalTimeFrame_nameLabel_QLabel = {"container": bottomBar_totalTimeFrame_ParameterValueBottomBarWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
averagePowerWidgetEmission_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseEnergyWidgetEmission_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
frequencyWidgetEmission_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
treatmentScreen_rightPedalWidget_PresetTabWidget = {"container": treatmentScreen_TreatmentScreen, "name": "rightPedalWidget", "type": "PresetTabWidget", "visible": 1}
rightPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget = {"container": treatmentScreen_rightPedalWidget_PresetTabWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget_2 = {"container": rightPedalWidget_qt_tabwidget_stackedwidget_QStackedWidget, "name": "OperationPresetWidget", "type": "OperationPresetWidget", "visible": 1}
operationPresetWidget_modeWidget_QFrame_2 = {"container": qt_tabwidget_stackedwidget_OperationPresetWidget_OperationPresetWidget_2, "name": "modeWidget", "type": "QFrame", "visible": 1}
modeWidget_PulseModeWidget_PulseModeWidget_2 = {"container": operationPresetWidget_modeWidget_QFrame_2, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "averagePowerWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
averagePowerWidgetEmission_nameLabel_QLabel_2 = {"container": pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
rightPedalWidget_TabBar = {"container": treatmentScreen_rightPedalWidget_PresetTabWidget, "type": "TabBar", "unnamed": 1, "visible": 1}
eNUKLEACIJA_PROSTATE_VELIKA_ENERGIJA_TabItem_2 = {"container": rightPedalWidget_TabBar, "text": "ENUKLEACIJA PROSTATE-(VELIKA ENERGIJA)", "type": "TabItem"}
pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "pulseEnergyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
pulseEnergyWidgetEmission_nameLabel_QLabel_2 = {"container": pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "frequencyWidgetEmission", "type": "ParameterWithBoundedValueWidget", "visible": 1}
frequencyWidgetEmission_nameLabel_QLabel_2 = {"container": pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_peakPowerButtonEmission_ParameterSettingsButton_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "peakPowerButtonEmission", "type": "ParameterSettingsButton", "visible": 1}
peakPowerButtonEmission_nameLabel_QLabel_2 = {"container": pulseModeWidget_peakPowerButtonEmission_ParameterSettingsButton_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_modeButtonEmission_ModeButton_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "modeButtonEmission", "type": "ModeButton", "visible": 1}
modeButtonEmission_nameLabel_QLabel_2 = {"container": pulseModeWidget_modeButtonEmission_ModeButton_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
bottomBar_fiberFrame_FiberInfoWidget = {"container": treatmentScreen_bottomBar_QFrame, "name": "fiberFrame", "type": "FiberInfoWidget", "visible": 1}
fiberFrame_nameLabel_QLabel = {"container": bottomBar_fiberFrame_FiberInfoWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
fiberFrame_valueFrame_QuantityLabel = {"container": bottomBar_fiberFrame_FiberInfoWidget, "name": "valueFrame", "type": "QuantityLabel", "visible": 1}
valueFrame_valueLabel_QLabel = {"container": fiberFrame_valueFrame_QuantityLabel, "name": "valueLabel", "type": "QLabel", "visible": 1}
bottomBar_aimingBeamButton_AimingBeamModeButton = {"container": treatmentScreen_bottomBar_QFrame, "name": "aimingBeamButton", "type": "AimingBeamModeButton", "visible": 1}
stateSwitch_standbyButton_QPushButton = {"container": bottomBar_stateSwitch_StateSwitch, "name": "standbyButton", "type": "QPushButton", "visible": 1}
averagePowerWidgetEmission_unitsOfMeasureLabel_QLabel_2 = {"container": pulseModeWidget_averagePowerWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseEnergyWidgetEmission_unitsOfMeasureLabel_QLabel_2 = {"container": pulseModeWidget_pulseEnergyWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
frequencyWidgetEmission_unitsOfMeasureLabel_QLabel_2 = {"container": pulseModeWidget_frequencyWidgetEmission_ParameterWithBoundedValueWidget_2, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}

treatmentScreen_topBar_TopBar = {"container": treatmentScreen_TreatmentScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar_2 = {"container": treatmentScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
leftPedalWidget_wdPresetTabs_TabWidget = {"container": treatmentScreen_leftPedalWidget_PresetTabWidget, "name": "wdPresetTabs", "type": "TabWidget", "visible": 1}
buttonsBar_homeButton_QPushButton_2 = {"container": topBar_buttonsBar_ButtonsBar_2, "name": "homeButton", "type": "QPushButton", "visible": 1}
quickStartScreen_topBar_TopBar = {"container": quickStartScreen_QuickStartScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar_3 = {"container": quickStartScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
quickStartScreen_wdTabWidgets_QWidget = {"container": quickStartScreen_QuickStartScreen, "name": "wdTabWidgets", "type": "QWidget", "visible": 1}
pulseModeWidget_peakPowerButton_ParameterSettingsButton = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "peakPowerButton", "type": "ParameterSettingsButton", "visible": 1}
peakPowerButton_nameLabel_QLabel = {"container": pulseModeWidget_peakPowerButton_ParameterSettingsButton, "name": "nameLabel", "type": "QLabel", "visible": 1}
centralWidget_QFrame = {"name": "centralWidget", "type": "QFrame", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_lbTitle_QLabel = {"container": centralWidget_QFrame, "name": "lbTitle", "type": "QLabel", "visible": 1}
centralWidget_pw500_QPushButton = {"container": centralWidget_QFrame, "name": "pw500", "type": "QPushButton", "visible": 1}
centralWidget_pw250_QPushButton = {"container": centralWidget_QFrame, "name": "pw250", "type": "QPushButton", "visible": 1}
centralWidget_pw125_QPushButton = {"container": centralWidget_QFrame, "name": "pw125", "type": "QPushButton", "visible": 1}
centralWidget_buttonsFrame_QFrame_2 = {"container": centralWidget_QFrame, "name": "buttonsFrame", "type": "QFrame", "visible": 1}
buttonsFrame_rejectButton_QPushButton = {"container": centralWidget_buttonsFrame_QFrame_2, "name": "rejectButton", "type": "QPushButton", "visible": 1}
settingsScreen_pbBack_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "pbBack", "type": "QPushButton", "visible": 1}
peakPowerButton_iconLabel_QLabel = {"container": pulseModeWidget_peakPowerButton_ParameterSettingsButton, "name": "iconLabel", "type": "QLabel", "visible": 1}
backgroundShadowWidget_QWidget = {"name": "backgroundShadowWidget", "type": "QWidget", "visible": 1, "window": o_ScreenSwitcher}
homeScreen_gbExpert_QFrame = {"container": homeScreen_HomeScreen, "name": "gbExpert", "type": "QFrame", "visible": 1}
gbExpert_expertButton_QPushButton = {"container": homeScreen_gbExpert_QFrame, "name": "expertButton", "type": "QPushButton", "visible": 1}
pulseModeWidget_modeButton_ModeButton = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "modeButton", "type": "ModeButton", "visible": 1}
modeButton_nameLabel_QLabel = {"container": pulseModeWidget_modeButton_ModeButton, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_modeButton_ModeButton_2 = {"container": modeWidget_PulseModeWidget_PulseModeWidget_2, "name": "modeButton", "type": "ModeButton", "visible": 1}
modeButton_nameLabel_QLabel_2 = {"container": pulseModeWidget_modeButton_ModeButton_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
centralWidget_CW_QPushButton = {"container": centralWidget_QFrame, "name": "CW", "type": "QPushButton", "visible": 1}
centralWidget_QFrame_2 = {"name": "centralWidget", "occurrence": 2, "type": "QFrame", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_CancelButton_QPushButton = {"container": centralWidget_QFrame_2, "name": "CancelButton", "type": "QPushButton", "visible": 1}
centralWidget_mainWidget_QWidget = {"container": centralWidget_QFrame, "name": "mainWidget", "type": "QWidget", "visible": 1}
centralWidget_Square_QPushButton = {"container": centralWidget_QFrame, "name": "Square", "type": "QPushButton", "visible": 1}
centralWidget_MRP_QPushButton = {"container": centralWidget_QFrame, "name": "MRP", "type": "QPushButton", "visible": 1}
centralWidget_Cleaning_QPushButton = {"container": centralWidget_QFrame, "name": "Cleaning", "type": "QPushButton", "visible": 1}
centralWidget_Enucleation_QPushButton = {"container": centralWidget_QFrame, "name": "Enucleation", "type": "QPushButton", "visible": 1}
centralWidget_Fragmentation_QPushButton = {"container": centralWidget_QFrame, "name": "Fragmentation", "type": "QPushButton", "visible": 1}
square_icon_QPushButton = {"name": "Square_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_OKButton_QPushButton = {"container": centralWidget_QFrame_2, "name": "OKButton", "type": "QPushButton", "visible": 1}
cW_icon_QPushButton = {"name": "CW_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
mRP_icon_QPushButton = {"name": "MRP_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
fragmentation_icon_QPushButton = {"name": "Fragmentation_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
cleaning_icon_QPushButton = {"name": "Cleaning_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
enucleation_icon_QPushButton = {"name": "Enucleation_icon", "type": "QPushButton", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_label_2_QLabel = {"container": centralWidget_QFrame, "name": "label_2", "type": "QLabel", "visible": 1}
centralWidget_label_QLabel = {"container": centralWidget_QFrame, "name": "label", "type": "QLabel", "visible": 1}
centralWidget_QFrame_3 = {"name": "centralWidget", "occurrence": 3, "type": "QFrame", "visible": 1, "window": o_ScreenSwitcher}
centralWidget_TitleLabel_QLabel = {"container": centralWidget_QFrame_3, "name": "TitleLabel", "type": "QLabel", "visible": 1}
centralWidget_MessageLabel_QLabel = {"container": centralWidget_QFrame_3, "name": "MessageLabel", "type": "QLabel", "visible": 1}
centralWidget_CancelButton_QPushButton_2 = {"container": centralWidget_QFrame_3, "name": "CancelButton", "type": "QPushButton", "visible": 1}
centralWidget_DisableButton_QPushButton = {"container": centralWidget_QFrame_3, "name": "DisableButton", "type": "QPushButton", "visible": 1}
centralWidget_OKButton_QPushButton_2 = {"container": centralWidget_QFrame_3, "name": "OKButton", "type": "QPushButton", "visible": 1}
gbSystemInformation_widget_QWidget = {"container": wdSystemInfoLayout_gbSystemInformation_QGroupBox, "name": "widget", "type": "QWidget", "visible": 1}
mainFrame_messageLabel_QLabel = {"container": recommendedFiberWarningDialog_mainFrame_QFrame, "name": "messageLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget = {"container": modeWidget_PulseModeWidget_PulseModeWidget, "name": "pulseEnergyWidget", "type": "ParameterSettingsWidget", "visible": 1}
pulseEnergyWidget_indexPicker_SliderAdaptor = {"container": pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget, "name": "indexPicker", "type": "SliderAdaptor", "visible": 1}
indexPicker_valuePicker_IntervalSlider = {"container": pulseEnergyWidget_indexPicker_SliderAdaptor, "name": "valuePicker", "type": "IntervalSlider", "visible": 1}
centralWidget_DisableButton_QPushButton_2 = {"container": centralWidget_QFrame, "name": "DisableButton", "type": "QPushButton", "visible": 1}
homeScreen_pbSoftTissueAssistant_QToolButton = {"container": homeScreen_HomeScreen, "name": "pbSoftTissueAssistant", "type": "QToolButton", "visible": 1}
softTissueAssistantModeScreen_SoftTissueAssistantModeScreen = {"name": "SoftTissueAssistantModeScreen", "type": "SoftTissueAssistantModeScreen", "visible": 1, "window": o_ScreenSwitcher}
softTissueAssistantModeScreen_gbSoftTissueProcedures_QFrame = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "gbSoftTissueProcedures", "type": "QFrame", "visible": 1}
gbSoftTissueProcedures_pbIncision_QPushButton = {"container": softTissueAssistantModeScreen_gbSoftTissueProcedures_QFrame, "name": "pbIncision", "type": "QPushButton", "visible": 1}
softTissueAssistantModeScreen_pbContinue_QPushButton = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "pbContinue", "type": "QPushButton", "visible": 1}
pulseEnergyWidget_incrementButton_QPushButton = {"container": pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget, "name": "incrementButton", "type": "QPushButton", "visible": 1}
treatmentScreen_TreatmentCharacteristicsBar_SoftTissueCharacteristicsBar = {"container": treatmentScreen_TreatmentScreen, "name": "TreatmentCharacteristicsBar", "type": "SoftTissueCharacteristicsBar", "visible": 1}
treatmentCharacteristicsBar_pbEdit_QPushButton = {"container": treatmentScreen_TreatmentCharacteristicsBar_SoftTissueCharacteristicsBar, "name": "pbEdit", "type": "QPushButton", "visible": 1}
centralWidget_titleLabel_QLabel = {"container": centralWidget_QFrame, "name": "titleLabel", "type": "QLabel", "visible": 1}
centralWidget_titleLabel_QLabel_2 = {"container": centralWidget_QFrame, "name": "titleLabel", "occurrence": 2, "type": "QLabel", "visible": 1}
centralWidget_valueLabel_QLabel = {"container": centralWidget_QFrame, "name": "valueLabel", "type": "QLabel", "visible": 1}
centralWidget_rejectButton_QPushButton = {"container": centralWidget_QFrame, "name": "rejectButton", "type": "QPushButton", "visible": 1}
centralWidget_acceptButton_QPushButton = {"container": centralWidget_QFrame, "name": "acceptButton", "type": "QPushButton", "visible": 1}
settingsScreen_addButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "addButton", "type": "QPushButton", "visible": 1}
centralWidget_pbName_QPushButton = {"container": centralWidget_QFrame, "name": "pbName", "type": "QPushButton", "visible": 1}
keyboardPopup_KeyboardPopup = {"name": "KeyboardPopup", "type": "KeyboardPopup", "visible": 1}
keyboardPopup_wdEdit_WdLineEdit = {"container": keyboardPopup_KeyboardPopup, "name": "wdEdit", "type": "WdLineEdit", "visible": 1}
keyboardPopup_lbText_QLabel = {"container": keyboardPopup_KeyboardPopup, "name": "lbText", "occurrence": 2, "type": "QLabel", "visible": 1}
centralWidget_PulseModeWidget_PulseModeWidget = {"container": centralWidget_QFrame, "name": "PulseModeWidget", "type": "PulseModeWidget", "visible": 1}
pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget_2 = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "pulseEnergyWidget", "type": "ParameterSettingsWidget", "visible": 1}
pulseEnergyWidget_indexPicker_SliderAdaptor_2 = {"container": pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget_2, "name": "indexPicker", "type": "SliderAdaptor", "visible": 1}
indexPicker_valuePicker_IntervalSlider_2 = {"container": pulseEnergyWidget_indexPicker_SliderAdaptor_2, "name": "valuePicker", "type": "IntervalSlider", "visible": 1}
pulseModeWidget_saveButton_QPushButton = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "saveButton", "type": "QPushButton", "visible": 1}
qt_tabwidget_stackedwidget_wdPresetsLayout_QWidget = {"container": settingsScreen_qt_tabwidget_stackedwidget_QStackedWidget, "name": "wdPresetsLayout", "type": "QWidget", "visible": 1}
wdPresetsLayout_qt_tabwidget_stackedwidget_QStackedWidget = {"container": qt_tabwidget_stackedwidget_wdPresetsLayout_QWidget, "name": "qt_tabwidget_stackedwidget", "type": "QStackedWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabSettingsPresetsUserStonePresets_QWidget = {"container": wdPresetsLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabSettingsPresetsUserStonePresets", "type": "QWidget", "visible": 1}
tabSettingsPresetsUserStonePresets_presetListView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabSettingsPresetsUserStonePresets_QWidget, "name": "presetListView", "type": "PresetListView", "visible": 1}
settingsScreen_editButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "editButton", "type": "QPushButton", "visible": 1}
settingsScreen_deletePresetButton_QPushButton = {"container": settingsScreen_SettingsScreen, "name": "deletePresetButton", "type": "QPushButton", "visible": 1}
centralWidget_lbOperation_QLabel = {"container": centralWidget_QFrame, "name": "lbOperation", "type": "QLabel", "visible": 1}
pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "averagePowerWidget", "type": "ParameterWithEnumerableValueWidget", "visible": 1}
averagePowerWidget_nameLabel_QLabel = {"container": pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
averagePowerWidget_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_averagePowerWidget_ParameterWithEnumerableValueWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseEnergyWidget_nameLabel_QLabel = {"container": pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseEnergyWidget_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_pulseEnergyWidget_ParameterSettingsWidget_2, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_frequencyWidget_ParameterSettingsWidget = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "frequencyWidget", "type": "ParameterSettingsWidget", "visible": 1}
frequencyWidget_nameLabel_QLabel = {"container": pulseModeWidget_frequencyWidget_ParameterSettingsWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
frequencyWidget_unitsOfMeasureLabel_QLabel = {"container": pulseModeWidget_frequencyWidget_ParameterSettingsWidget, "name": "unitsOfMeasureLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_modeButton_ModeButton_3 = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "modeButton", "type": "ModeButton", "visible": 1}
modeButton_nameLabel_QLabel_3 = {"container": pulseModeWidget_modeButton_ModeButton_3, "name": "nameLabel", "type": "QLabel", "visible": 1}
pulseModeWidget_peakPowerButton_ParameterSettingsButton_2 = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "peakPowerButton", "type": "ParameterSettingsButton", "visible": 1}
peakPowerButton_nameLabel_QLabel_2 = {"container": pulseModeWidget_peakPowerButton_ParameterSettingsButton_2, "name": "nameLabel", "type": "QLabel", "visible": 1}
centralWidget_okButton_QPushButton = {"container": centralWidget_QFrame_2, "name": "okButton", "type": "QPushButton", "visible": 1}
keyboardPopup_p_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "p", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_r_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "r", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_e_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "e", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_s_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "s", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_t_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "t", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_123_Brojevi_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "&123\nBrojevi", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": ".", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_KeyButton_2 = {"aboveWidget": keyboardPopup_123_Brojevi_KeyButton, "container": keyboardPopup_KeyboardPopup, "leftWidget": keyboardPopup_KeyButton, "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_o_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "o", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_n_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "n", "type": "KeyButton", "unnamed": 1, "visible": 1}
wdPresetsLayout_tabBarPresetsForSettings_TabBar = {"container": qt_tabwidget_stackedwidget_wdPresetsLayout_QWidget, "name": "tabBarPresetsForSettings", "type": "TabBar", "visible": 1}
tabBarPresetsForSettings_KAMEN_TabItem = {"container": wdPresetsLayout_tabBarPresetsForSettings_TabBar, "text": "KAMEN", "type": "TabItem"}
tabBarPresetsForSettings_MEKO_TKIVO_TabItem = {"container": wdPresetsLayout_tabBarPresetsForSettings_TabBar, "text": "MEKO TKIVO", "type": "TabItem"}
centralWidget_lbDialogTitle_QLabel = {"container": centralWidget_QFrame, "name": "lbDialogTitle", "type": "QLabel", "visible": 1}
centralWidget_questionLabel_QLabel = {"container": centralWidget_QFrame, "name": "questionLabel", "type": "QLabel", "visible": 1}
centralWidget_infoFrame_QFrame = {"container": centralWidget_QFrame, "name": "infoFrame", "type": "QFrame", "visible": 1}
infoFrame_extInfoLabel_QLabel = {"container": centralWidget_infoFrame_QFrame, "name": "extInfoLabel", "type": "QLabel", "visible": 1}
centralWidget_backgroundWidget_QWidget = {"container": centralWidget_QFrame, "name": "backgroundWidget", "type": "QWidget", "visible": 1}
languagesFrame_pbCzech_QPushButton = {"container": centralWidget_languagesFrame_QFrame, "name": "pbCzech", "type": "QPushButton", "visible": 1}
eNUKLEACE_PROSTATY_VYSOK_ENERGIE_TabItem = {"container": leftPedalWidget_TabBar, "text": "ENUKLEACE PROSTATY-(VYSOKÁ ENERGIE)", "type": "TabItem"}
quickStartScreen_wdBottom_QWidget = {"container": quickStartScreen_QuickStartScreen, "name": "wdBottom", "type": "QWidget", "visible": 1}
eNUKLEACE_PROSTATY_VYSOK_ENERGIE_TabItem_2 = {"container": rightPedalWidget_TabBar, "text": "ENUKLEACE PROSTATY-(VYSOKÁ ENERGIE)", "type": "TabItem"}
bottomBar_fiberUsesFrame_ParameterValueBottomBarWidget = {"container": treatmentScreen_bottomBar_QFrame, "name": "fiberUsesFrame", "type": "ParameterValueBottomBarWidget", "visible": 1}
fiberUsesFrame_nameLabel_QLabel = {"container": bottomBar_fiberUsesFrame_ParameterValueBottomBarWidget, "name": "nameLabel", "type": "QLabel", "visible": 1}
centralWidget_CancelButton_QPushButton_3 = {"container": centralWidget_QFrame, "name": "CancelButton", "type": "QPushButton", "visible": 1}
rightPedalWidget_wdPresetTabs_TabWidget = {"container": treatmentScreen_rightPedalWidget_PresetTabWidget, "name": "wdPresetTabs", "type": "TabWidget", "visible": 1}
treatmentScreen_leftPedalWidgetBorder_QWidget = {"container": treatmentScreen_TreatmentScreen, "name": "leftPedalWidgetBorder", "type": "QWidget", "visible": 1}
wdLeftPedalTreatmentLayout_tbLeftPedalPresets_TabWidget = {"container": qt_tabwidget_stackedwidget_wdLeftPedalTreatmentLayout_QWidget, "name": "tbLeftPedalPresets", "type": "TabWidget", "visible": 1}
qt_tabwidget_stackedwidget_tabLeftUserPresets_QWidget = {"container": wdLeftPedalTreatmentLayout_qt_tabwidget_stackedwidget_QStackedWidget, "name": "tabLeftUserPresets", "type": "QWidget", "visible": 1}
tabLeftUserPresets_leftUserPresetsView_PresetListView = {"container": qt_tabwidget_stackedwidget_tabLeftUserPresets_QWidget, "name": "leftUserPresetsView", "type": "PresetListView", "visible": 1}
leftUserPresetsView_tabLeftUserPresetsView_QLabel = {"container": tabLeftUserPresets_leftUserPresetsView_PresetListView, "name": "tabLeftUserPresetsView", "type": "QLabel", "visible": 1}
centralWidget_TitleLabel_QLabel_2 = {"container": centralWidget_QFrame, "name": "TitleLabel", "type": "QLabel", "visible": 1}
centralWidget_MessageLabel_QLabel_2 = {"container": centralWidget_QFrame, "name": "MessageLabel", "type": "QLabel", "visible": 1}
softTissueAssistantModeScreen_topBar_TopBar = {"container": softTissueAssistantModeScreen_SoftTissueAssistantModeScreen, "name": "topBar", "type": "TopBar", "visible": 1}
topBar_buttonsBar_ButtonsBar_4 = {"container": softTissueAssistantModeScreen_topBar_TopBar, "name": "buttonsBar", "type": "ButtonsBar", "visible": 1}
buttonsBar_homeButton_QPushButton_3 = {"container": topBar_buttonsBar_ButtonsBar_4, "name": "homeButton", "type": "QPushButton", "visible": 1}
treatmentScreen_rightPedalWidgetBorder_QWidget = {"container": treatmentScreen_TreatmentScreen, "name": "rightPedalWidgetBorder", "type": "QWidget", "visible": 1}
centralWidget_TitleLabel_QLabel_3 = {"container": centralWidget_QFrame_2, "name": "TitleLabel", "type": "QLabel", "visible": 1}
centralWidget_MessageLabel_QLabel_3 = {"container": centralWidget_QFrame_2, "name": "MessageLabel", "type": "QLabel", "visible": 1}
keyboardPopup_KeyButton_3 = {"container": keyboardPopup_KeyboardPopup, "text": "⌫", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_123_sla_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "&123\nČísla", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_KeyButton_4 = {"aboveWidget": keyboardPopup_123_sla_KeyButton, "container": keyboardPopup_KeyboardPopup, "leftWidget": keyboardPopup_KeyButton, "type": "KeyButton", "unnamed": 1, "visible": 1}
tabBarPresetsForSettings_K_MEN_TabItem = {"container": wdPresetsLayout_tabBarPresetsForSettings_TabBar, "text": "KÁMEN", "type": "TabItem"}
tabBarPresetsForSettings_M_KK_TK_TabItem = {"container": wdPresetsLayout_tabBarPresetsForSettings_TabBar, "text": "MĚKKÁ TKÁŇ", "type": "TabItem"}
centralWidget_pbClose_QPushButton = {"container": centralWidget_QFrame, "name": "pbClose", "type": "QPushButton", "visible": 1}
languagesFrame_pbDenmark_QPushButton = {"container": centralWidget_languagesFrame_QFrame, "name": "pbDenmark", "type": "QPushButton", "visible": 1}
numpad_pushButton_1_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_1", "type": "NumpadButton", "visible": 1}
numpad_pushButton_2_NumpadButton = {"container": inputFrame_numpad_Numpad, "name": "pushButton_2", "type": "NumpadButton", "visible": 1}
inputFrame_backspaceButton_NumpadButton = {"container": gbPasscode_inputFrame_PasscodeInputWidget, "name": "backspaceButton", "type": "NumpadButton", "visible": 1}
centralWidget_frame_QFrame = {"container": centralWidget_QFrame, "name": "frame", "type": "QFrame", "visible": 1}
pulseModeWidget_buttonsWidget_QWidget = {"container": centralWidget_PulseModeWidget_PulseModeWidget, "name": "buttonsWidget", "type": "QWidget", "visible": 1}
pROSTATAENUKLEATION_H_J_ENERGI_TabItem = {"container": leftPedalWidget_TabBar, "text": "PROSTATAENUKLEATION-(HØJ ENERGI)", "type": "TabItem"}
pROSTATAENUKLEATION_H_J_ENERGI_TabItem_2 = {"container": rightPedalWidget_TabBar, "text": "PROSTATAENUKLEATION-(HØJ ENERGI)", "type": "TabItem"}
keyboardPopup_123_KeyButton = {"container": keyboardPopup_KeyboardPopup, "text": "&123", "type": "KeyButton", "unnamed": 1, "visible": 1}
keyboardPopup_KeyButton_5 = {"aboveWidget": keyboardPopup_123_KeyButton, "container": keyboardPopup_KeyboardPopup, "leftWidget": keyboardPopup_KeyButton, "type": "KeyButton", "unnamed": 1, "visible": 1}
